# Generated by Django 3.1.4 on 2021-01-04 18:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('content', models.FileField(upload_to='media')),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
